package client

import (
	"context"
	"fmt"

	"github.com/google/generative-ai-go/genai"
	"google.golang.org/api/option"

	"videoservice/internal/client/helpers"
)

type GeminiClient struct {
	client *genai.Client
	model  *genai.GenerativeModel
}

func NewGeminiClient(ctx context.Context, apiKey string) (*GeminiClient, error) {
	client, err := genai.NewClient(ctx, option.WithAPIKey(apiKey))
	if err != nil {
		return nil, fmt.Errorf("failed to create gemini client: %w", err)
	}

	// Use gemini-2.5-flash for fast and efficient summarization
	model := client.GenerativeModel("gemini-2.5-flash")

	return &GeminiClient{
		client: client,
		model:  model,
	}, nil
}

func (c *GeminiClient) Summarize(ctx context.Context, text string) (string, error) {
	if text == "" {
		return "", fmt.Errorf("empty transcript provided for summarization")
	}

	prompt := fmt.Sprintf(`Summarize the following transcript. 

	STRICT FORMATTING RULES:
	- Use standard Markdown only.
	- For bullet points, use a HYPHEN (-) followed by a SINGLE STANDARD SPACE.
	- DO NOT use non-breaking spaces or special indentation.
	- Double-space between paragraphs.

	Transcript:
	%s`, text)

	resp, err := c.model.GenerateContent(ctx, genai.Text(prompt))
	if err != nil {
		return "", fmt.Errorf("failed to generate summary from Gemini: %w", err)
	}

	if len(resp.Candidates) == 0 || resp.Candidates[0].Content == nil {
		return "", fmt.Errorf("no summary content generated by Gemini")
	}

	var result string
	for _, part := range resp.Candidates[0].Content.Parts {
		if textPart, ok := part.(genai.Text); ok {
			result += string(textPart)
		}
	}

	if result == "" {
		return "", fmt.Errorf("empty result parts from Gemini")
	}

	return helpers.SanitizeMarkdown(result), nil
}

func (c *GeminiClient) Close() error {
	return c.client.Close()
}
